// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhlb17XSNpnEBiONU1uu6vba_YpO2pLVA',
    appId: '1:459439556718:web:0c51af0cc7e4fa88abbe7f',
    messagingSenderId: '459439556718',
    projectId: 'travel-app-65ced',
    authDomain: 'travel-app-65ced.firebaseapp.com',
    storageBucket: 'travel-app-65ced.appspot.com',
    measurementId: 'G-31XQ74M3ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqgP14vfXkKzATrbQyOE-cD2fo1fhDC_Q',
    appId: '1:459439556718:android:edb2a80071bbb518abbe7f',
    messagingSenderId: '459439556718',
    projectId: 'travel-app-65ced',
    storageBucket: 'travel-app-65ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4CctavbW_BaZIpLZyNubMXYkW-On_FW8',
    appId: '1:459439556718:ios:7b35e56c181cc5b6abbe7f',
    messagingSenderId: '459439556718',
    projectId: 'travel-app-65ced',
    storageBucket: 'travel-app-65ced.appspot.com',
    androidClientId: '459439556718-5hk8u9g9uf1b93tu9b6nnv313ju6dkan.apps.googleusercontent.com',
    iosClientId: '459439556718-gt5a1gneqs4hsvd8c0in6rno1m9th8v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
